# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sidecar.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sidecar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsidecar.proto\x12\x0egeoclt.sidecar\"y\n\nTraceStart\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x12\n\nadapter_id\x18\x02 \x01(\t\x12\x10\n\x08model_id\x18\x03 \x01(\t\x12\x0f\n\x07lane_id\x18\x04 \x01(\t\x12\x0e\n\x06run_id\x18\x05 \x01(\t\x12\x12\n\nstarted_at\x18\x06 \x01(\t\"z\n\x0f\x41\x63tivationChunk\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x1d\n\x15\x63hunk_idempotency_key\x18\x02 \x01(\t\x12\x10\n\x08layer_id\x18\x03 \x01(\r\x12\x0f\n\x07payload\x18\x04 \x01(\x0c\x12\x13\n\x0bsequence_no\x18\x05 \x01(\x04\"2\n\x08TraceEnd\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x14\n\x0ctotal_chunks\x18\x02 \x01(\x04\".\n\nTraceAbort\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x0e\n\x06reason\x18\x02 \x01(\t\"N\n\x11\x41rtifactBundleRef\x12\x11\n\tbundle_id\x18\x01 \x01(\t\x12\x11\n\tstore_uri\x18\x02 \x01(\t\x12\x13\n\x0b\x62undle_hash\x18\x03 \x01(\t\"M\n\x0e\x41rtifactInline\x12\x11\n\tbundle_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62undle_json\x18\x02 \x01(\x0c\x12\x13\n\x0b\x62undle_hash\x18\x03 \x01(\t\"\"\n\x03\x41\x63k\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x04Nack\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"Y\n\x12\x42\x61\x63kpressureSignal\x12\x10\n\x08trace_id\x18\x01 \x01(\t\x12\x13\n\x0bqueue_depth\x18\x02 \x01(\r\x12\x1c\n\x14recommended_delay_ms\x18\x03 \x01(\r\"5\n\x0cServerStatus\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x15\n\ractive_traces\x18\x02 \x01(\r2\xdc\x02\n\x0eSidecarService\x12=\n\nStartTrace\x12\x1a.geoclt.sidecar.TraceStart\x1a\x13.geoclt.sidecar.Ack\x12\x46\n\x0ePushActivation\x12\x1f.geoclt.sidecar.ActivationChunk\x1a\x13.geoclt.sidecar.Ack\x12\x44\n\x08\x45ndTrace\x12\x18.geoclt.sidecar.TraceEnd\x1a\x1e.geoclt.sidecar.ArtifactInline\x12=\n\nAbortTrace\x12\x1a.geoclt.sidecar.TraceAbort\x1a\x13.geoclt.sidecar.Ack\x12>\n\tGetStatus\x12\x13.geoclt.sidecar.Ack\x1a\x1c.geoclt.sidecar.ServerStatusb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sidecar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACESTART']._serialized_start=33
  _globals['_TRACESTART']._serialized_end=154
  _globals['_ACTIVATIONCHUNK']._serialized_start=156
  _globals['_ACTIVATIONCHUNK']._serialized_end=278
  _globals['_TRACEEND']._serialized_start=280
  _globals['_TRACEEND']._serialized_end=330
  _globals['_TRACEABORT']._serialized_start=332
  _globals['_TRACEABORT']._serialized_end=378
  _globals['_ARTIFACTBUNDLEREF']._serialized_start=380
  _globals['_ARTIFACTBUNDLEREF']._serialized_end=458
  _globals['_ARTIFACTINLINE']._serialized_start=460
  _globals['_ARTIFACTINLINE']._serialized_end=537
  _globals['_ACK']._serialized_start=539
  _globals['_ACK']._serialized_end=573
  _globals['_NACK']._serialized_start=575
  _globals['_NACK']._serialized_end=612
  _globals['_BACKPRESSURESIGNAL']._serialized_start=614
  _globals['_BACKPRESSURESIGNAL']._serialized_end=703
  _globals['_SERVERSTATUS']._serialized_start=705
  _globals['_SERVERSTATUS']._serialized_end=758
  _globals['_SIDECARSERVICE']._serialized_start=761
  _globals['_SIDECARSERVICE']._serialized_end=1109
# @@protoc_insertion_point(module_scope)
