# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sidecar_pb2 as sidecar__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in sidecar_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SidecarServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTrace = channel.unary_unary(
                '/geoclt.sidecar.SidecarService/StartTrace',
                request_serializer=sidecar__pb2.TraceStart.SerializeToString,
                response_deserializer=sidecar__pb2.Ack.FromString,
                _registered_method=True)
        self.PushActivation = channel.unary_unary(
                '/geoclt.sidecar.SidecarService/PushActivation',
                request_serializer=sidecar__pb2.ActivationChunk.SerializeToString,
                response_deserializer=sidecar__pb2.Ack.FromString,
                _registered_method=True)
        self.EndTrace = channel.unary_unary(
                '/geoclt.sidecar.SidecarService/EndTrace',
                request_serializer=sidecar__pb2.TraceEnd.SerializeToString,
                response_deserializer=sidecar__pb2.ArtifactInline.FromString,
                _registered_method=True)
        self.AbortTrace = channel.unary_unary(
                '/geoclt.sidecar.SidecarService/AbortTrace',
                request_serializer=sidecar__pb2.TraceAbort.SerializeToString,
                response_deserializer=sidecar__pb2.Ack.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/geoclt.sidecar.SidecarService/GetStatus',
                request_serializer=sidecar__pb2.Ack.SerializeToString,
                response_deserializer=sidecar__pb2.ServerStatus.FromString,
                _registered_method=True)


class SidecarServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushActivation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortTrace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SidecarServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTrace,
                    request_deserializer=sidecar__pb2.TraceStart.FromString,
                    response_serializer=sidecar__pb2.Ack.SerializeToString,
            ),
            'PushActivation': grpc.unary_unary_rpc_method_handler(
                    servicer.PushActivation,
                    request_deserializer=sidecar__pb2.ActivationChunk.FromString,
                    response_serializer=sidecar__pb2.Ack.SerializeToString,
            ),
            'EndTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.EndTrace,
                    request_deserializer=sidecar__pb2.TraceEnd.FromString,
                    response_serializer=sidecar__pb2.ArtifactInline.SerializeToString,
            ),
            'AbortTrace': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortTrace,
                    request_deserializer=sidecar__pb2.TraceAbort.FromString,
                    response_serializer=sidecar__pb2.Ack.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=sidecar__pb2.Ack.FromString,
                    response_serializer=sidecar__pb2.ServerStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'geoclt.sidecar.SidecarService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('geoclt.sidecar.SidecarService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SidecarService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoclt.sidecar.SidecarService/StartTrace',
            sidecar__pb2.TraceStart.SerializeToString,
            sidecar__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushActivation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoclt.sidecar.SidecarService/PushActivation',
            sidecar__pb2.ActivationChunk.SerializeToString,
            sidecar__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EndTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoclt.sidecar.SidecarService/EndTrace',
            sidecar__pb2.TraceEnd.SerializeToString,
            sidecar__pb2.ArtifactInline.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortTrace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoclt.sidecar.SidecarService/AbortTrace',
            sidecar__pb2.TraceAbort.SerializeToString,
            sidecar__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/geoclt.sidecar.SidecarService/GetStatus',
            sidecar__pb2.Ack.SerializeToString,
            sidecar__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
